const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST'
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'
const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART'
const BOOK_REMOVE_FROM_CART = 'BOOK_REMOVE_FROM_CART'
const BOOK_DELETE_FROM_CART = 'BOOK_DELETE_FROM_CART'



export {
    FETCH_BOOKS_REQUEST,
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_FAILURE,
    BOOK_ADDED_TO_CART,
    BOOK_REMOVE_FROM_CART,
    BOOK_DELETE_FROM_CART,
}